### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [php1301/NBTechInterview#3]
Hello Potter 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would also love to hear back from you. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us immediately so we can plan accordingly.

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I completed the first round of reviews but could not run the application locally due to #4. In addition, as a general comment, the codebase is a bit hard to navigate at the moment:
- There are many console.log statements and commented code blocks
- There are no line breaks in the application code (the code needs to breath a bit  🌬️ )

https://github.com/php1301/NBTechInterview/blob/26e25361c17bf4bab26e3b457be1d8d3d3e4e1ce/src/components/search/index.tsx#L38-L53

IT would be easier to go through in the following format:

```javascript
setUploading(true); 

 const reader = new FileReader(); 

 reader.onloadend = async ({ target }) => { 
     const csv = await Papa.parse(target?.result, { header: true }); 

     setSearch(csv?.data?.slice(0, -1)); 

     const results = await axios.post("/api/search", { 
         payload: { 
             user, 
             keywords: csv?.data?.slice(0, -1), 
         }, 
     }); 

     const finalizedResult: SearchResponseType = results?.data?.results; 
     setResult(finalizedResult); 
 }; 
```

I will now await for your feedback on the open issues.

**Comment by php1301** [comment]
Thank you for your time. I'm actively making improvements based on your feedback.

**Comment by olivierobert** [comment]
Thank you for your feedback and fixes. Your efforts are appreciated 🙏 

It is now time to wrap up this stage of the application process. Our team will communicate by email the status of your application shortly.
