### ISSUE TITLE
[Question] Abscence of ORM usage 

### ISSUE THREAD

**Issue by olivierobert** [php1301/NBTechInterview#6]
## Issue

The current implementation solely relies on the NPM package for Postgres. Hence, all database queries are hard coded and unsafe (some are open to SQL injections). 

https://github.com/php1301/NBTechInterview/blob/26e25361c17bf4bab26e3b457be1d8d3d3e4e1ce/pages/api/user-search/index.ts#L8-L18

Why not use battle-tested solutions such as [Prisma](https://www.prisma.io/) or [TypeORM](https://typeorm.io/)?

**Comment by php1301** [comment]
Thanks. I will try to refactor with the ORM approach, cause I think for this scope of Interview this ORM would be quite overengineering.

**Comment by olivierobert** [comment]
Not reinventing the wheel and using the right tool for the job is definitely part of the assessment 😉

**Comment by php1301** [comment]
Migrated to Prisma ORM now.
#8 Fix Issues PR
